import Image from "next/image";
import Link from "next/link";
import type { Locale } from "../lib/i18n";
import { getRoute } from "../lib/routes";
import type { VehicleListing } from "../lib/types";

interface VehicleCardProps {
	vehicle: VehicleListing;
	locale: Locale;
	cta: string;
}

export default function VehicleCard({
	vehicle,
	locale,
	cta,
}: VehicleCardProps) {
	const formatPrice = (price: number) =>
		new Intl.NumberFormat(locale, {
			style: "currency",
			currency: "EUR",
			maximumFractionDigits: 0,
		}).format(price);

	const formatNumber = (num: number) =>
		new Intl.NumberFormat(locale).format(num);

	const detailHref = `${getRoute("vehicles", locale)}/${vehicle.slug}`;
	const isSold = !vehicle.isAvailable;

	// Title construction: Make Model Subtitle
	// If subtitle is present, it's often the "Version" or "Trim"
	// If not, we just use Make Model
	// Actually, WP title usually contains everything. Let's use vehicle.title as primary,
	// or construct it if title is too long/messy?
	// User asked for "Marka + Model + wersja krótka".
	// WP title.rendered usually comes from "Make Model Version" auto-generated by some plugins or manual.
	// Let's stick to vehicle.title for now as it's reliable, or compose if needed.
	// We will assume vehicle.title is good.

	return (
		<Link href={detailHref} className="block group h-full" prefetch={false}>
			<article className="h-full flex flex-col bg-white rounded-2xl shadow-sm border border-gray-100 overflow-hidden transition-all duration-300 hover:shadow-xl hover:-translate-y-1">
				{/* IMAGE PLACEMENT */}
				<div className="relative h-56 w-full bg-gray-100 overflow-hidden">
					{/* Badges Overlay */}
					<div className="absolute top-3 left-3 z-10 flex gap-2">
						<span className="bg-gray-900/80 backdrop-blur-sm text-white text-[10px] font-bold px-2 py-1 rounded uppercase tracking-wider">
							{vehicle.category}
						</span>
					</div>

					<div className="absolute top-3 right-3 z-10">
						{isSold ? (
							<span className="bg-red-600 text-white text-[10px] font-bold px-2 py-1 rounded uppercase shadow-sm">
								{locale === "pl"
									? "Sprzedany"
									: locale === "en"
										? "Sold"
										: "Verkauft"}
							</span>
						) : (
							<span className="bg-emerald-500 text-white text-[10px] font-bold px-2 py-1 rounded uppercase shadow-sm">
								{locale === "pl"
									? "Dostępny"
									: locale === "en"
										? "Available"
										: "Verfügbar"}
							</span>
						)}
					</div>

					{vehicle.image ? (
						<Image
							src={vehicle.image}
							alt={vehicle.title}
							fill
							className={`object-cover transition-transform duration-700 group-hover:scale-105 ${isSold ? "grayscale" : ""}`}
							sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw"
						/>
					) : (
						<div className="flex h-full items-center justify-center text-gray-400 bg-gray-50">
							<svg
								className="w-12 h-12 opacity-20"
								fill="none"
								stroke="currentColor"
								viewBox="0 0 24 24"
							>
								<path
									strokeLinecap="round"
									strokeLinejoin="round"
									strokeWidth="2"
									d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z"
								/>
							</svg>
						</div>
					)}
				</div>

				{/* CONTENT */}
				<div className="p-5 flex flex-col flex-grow">
					{/* Title */}
					<h3 className="text-lg font-bold text-gray-900 line-clamp-2 leading-tight mb-4 min-h-[3rem] group-hover:text-brand-primary transition-colors">
						{vehicle.title}
					</h3>

					{/* Specs Grid */}
					<div className="grid grid-cols-2 gap-y-2 gap-x-4 text-sm text-gray-600 mb-6">
						<div className="flex items-center gap-2">
							<svg
								className="w-4 h-4 text-gray-400 shrink-0"
								fill="none"
								viewBox="0 0 24 24"
								stroke="currentColor"
							>
								<path
									strokeLinecap="round"
									strokeLinejoin="round"
									strokeWidth="2"
									d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z"
								/>
							</svg>
							<span>{vehicle.year}</span>
						</div>
						<div className="flex items-center gap-2">
							<svg
								className="w-4 h-4 text-gray-400 shrink-0"
								fill="none"
								viewBox="0 0 24 24"
								stroke="currentColor"
							>
								<path
									strokeLinecap="round"
									strokeLinejoin="round"
									strokeWidth="2"
									d="M13 10V3L4 14h7v7l9-11h-7z"
								/>
							</svg>
							<span className="truncate">{vehicle.power}</span>
						</div>
						<div className="flex items-center gap-2">
							<svg
								className="w-4 h-4 text-gray-400 shrink-0"
								fill="none"
								viewBox="0 0 24 24"
								stroke="currentColor"
							>
								<path
									strokeLinecap="round"
									strokeLinejoin="round"
									strokeWidth="2"
									d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z"
								/>
							</svg>
							<span>{formatNumber(vehicle.mileage)} km</span>
						</div>
						<div className="flex items-center gap-2">
							<svg
								className="w-4 h-4 text-gray-400 shrink-0"
								fill="none"
								viewBox="0 0 24 24"
								stroke="currentColor"
							>
								<path
									strokeLinecap="round"
									strokeLinejoin="round"
									strokeWidth="2"
									d="M19.428 15.428a2 2 0 00-1.022-.547l-2.384-.477a6 6 0 00-3.86.517l-.318.158a6 6 0 01-3.86.517L6.05 15.21a2 2 0 00-1.806.547M8 4h8l-1 1v5.172a2 2 0 00.586 1.414l5 5c1.26 1.26.367 3.414-1.415 3.414H4.828c-1.782 0-2.674-2.154-1.414-3.414l5-5A2 2 0 009 10.172V5L8 4z"
								/>
							</svg>
							<span className="truncate capitalize">{vehicle.fuel}</span>
						</div>
						<div className="flex items-center gap-2 col-span-2">
							<svg
								className="w-4 h-4 text-gray-400 shrink-0"
								fill="none"
								viewBox="0 0 24 24"
								stroke="currentColor"
							>
								<path
									strokeLinecap="round"
									strokeLinejoin="round"
									strokeWidth="2"
									d="M12 6V4m0 2a2 2 0 100 4m0-4a2 2 0 110 4m-6 8a2 2 0 100-4m0 4a2 2 0 110-4m0 4v2m0-6V4m6 6v10m6-2a2 2 0 100-4m0 4a2 2 0 110-4m0 4v2m0-6V4"
								/>
							</svg>
							<span className="truncate capitalize">
								{vehicle.transmission}
							</span>
						</div>
					</div>

					<div className="mt-auto pt-4 border-t border-gray-100 flex items-end justify-between">
						<div>
							{vehicle.priceStatus === "Auf Anfrage" ||
							vehicle.priceGross === 0 ? (
								<span className="text-xl font-bold text-gray-900">
									{locale === "pl"
										? "Na zapytanie"
										: locale === "en"
											? "On Request"
											: "Auf Anfrage"}
								</span>
							) : (
								<>
									<span className="text-2xl font-extrabold text-[#d32f2f] block leading-none">
										{formatPrice(vehicle.priceGross)}
									</span>
									{(vehicle.priceNetto ?? 0) > 0 &&
										vehicle.priceGross !== vehicle.priceNetto && (
											<div className="mt-1 flex items-center gap-2">
												<span className="bg-gray-100 text-gray-600 text-[10px] font-bold px-1.5 py-0.5 rounded border border-gray-200 uppercase">
													Netto
												</span>
												<span className="text-xs text-gray-500 font-medium">
													{formatPrice(vehicle.priceNetto!)}
												</span>
											</div>
										)}
									{/* If no netto but standard VAT, maybe show Brut to imply */}
								</>
							)}
						</div>

						{/* Simple arrow CTA */}
						<div className="w-8 h-8 rounded-full bg-gray-50 flex items-center justify-center group-hover:bg-brand-primary group-hover:text-white transition-colors text-gray-400">
							<svg
								className="w-4 h-4"
								fill="none"
								stroke="currentColor"
								viewBox="0 0 24 24"
							>
								<path
									strokeLinecap="round"
									strokeLinejoin="round"
									strokeWidth="2"
									d="M9 5l7 7-7 7"
								/>
							</svg>
						</div>
					</div>
				</div>
			</article>
		</Link>
	);
}
